#!/bin/bash -eu

# shellcheck disable=2015,2086

echo "=> Formatting code"
ruff format "$@"

echo "=> Formatting scripts"
shfmt --indent 2 --write .github/scripts/ cuda/ format setup

echo "=> Sorting imports"
ruff check --select I --fix "$@"

echo "=> Formatting JSON"
find "$@" -not -path "*/.*" -type f -name "*.json" -o -name "*.jsonschema" | while read -r f; do
  jq -S . $f >$f.new || (echo "    in $f" && rm $f.new && false)
  cmp --quiet $f.new $f && rm $f.new || mv $f.new $f
done
