# This is the Global EAGLE case.

# yamllint disable rule:anchors rule:line-length

inference:
  anemoi:
    input_dataset_kwargs: &dataset-kwargs
      dataset: '{{ grids_and_meshes.rundir }}/gfs.zarr'
prewxvx:
  common:
    prewxvx: &prewxvx-common
      forecast_path: '{{ inference.anemoi.output_path }}'
      freq: '{{ app.time.freq }}'
      lead_time: !int '{{ app.time.leadtime }}'
      lam_index: 64220
      lcc_info:
        n_x: 338
        n_y: 190
      levels:
        - 250
        - 500
        - 850
      start_date: '{{ app.time.inference_start }}'
      end_date: '{{ app.time.inference_stop }}'
      vars_of_interest: !list '{{ vx.common.wxvx.variables.keys() | list }}'
    rundir: '{{ val.vx.rundir }}'
  global:
    prewxvx: &prewxvx-global
      name: global
      eagle_tools:
        <<: *prewxvx-common
        output_path: '{{ val.vx.rundir }}/postprocessed_files/{{ prewxvx.global.prewxvx.name }}'
        model_type: global
        anemoi_reference_dataset_kwargs:
          <<: *dataset-kwargs
        forecast_regrid_kwargs:
          regridder_kwargs:
            method: 'conservative_normed'
          target_grid_path: '{{ val.data.rundir }}/{{ val.filenames.gfs_target_grid }}'
      rundir: '{{ val.vx.rundir }}/prewxvx/{{ prewxvx.global.prewxvx.name }}'
training:
  anemoi:
    defaults:
      - data: zarr
      - dataloader: native_grid
      - diagnostics: evaluation
      - graph: encoder_decoder_only
      - model: transformer
      - system: slurm
      - training: stretched
      - _self_
    # Blocks to customize default Anemoi training config.
    data:
      datasets:
        data:
          diagnostic:
            - accum_tp
            - u80
            - v80
          forcing:
            - cos_latitude
            - sin_latitude
            - cos_longitude
            - sin_longitude
            - cos_julian_day
            - sin_julian_day
            - cos_local_time
            - sin_local_time
            - insolation
            - lsm
            - orog
          processors:
            normalizer:
              _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
              config:
                default: mean-std
                max:
                  - orog
                none:
                  - cos_latitude
                  - sin_latitude
                  - cos_longitude
                  - sin_longitude
                  - cos_julian_day
                  - sin_julian_day
                  - cos_local_time
                  - sin_local_time
                  - insolation
                  - lsm
                std:
                  - accum_tp
                  - sh2
                  - q_100
                  - q_150
                  - q_200
                  - q_250
                  - q_300
                  - q_400
                  - q_500
                  - q_600
                  - q_700
                  - q_850
                  - q_925
                  - q_1000
    dataloader:
      batch_size:
        test: 1
        training: 1
        validation: 1
      dataset:
        dataset: '{{ val.data.rundir }}/gfs.zarr'
      limit_batches:
        training: null
        validation: null
      prefetch_factor: 1
      num_workers:
        test: 1
        training: 1
        validation: 1
      test:
        datasets:
          data:
            dataset_config:
              dataset: ${dataloader.dataset}
              frequency: ${data.frequency}
            start: '{{ (app.time.start + app.time.step * 16).strftime("%Y-%m-%d") }}'
            end: '{{ (app.time.start + app.time.step * 20).strftime("%Y-%m-%d") }}'
      training:
        datasets:
          data:
            dataset_config:
              dataset: ${dataloader.dataset}
              frequency: ${data.frequency}
            start: '{{ app.time.start.strftime("%Y-%m-%d") }}'
            end: '{{ (app.time.start + app.time.step * 4).strftime("%Y-%m-%d") }}'
      validation:
        datasets:
          data:
            dataset_config:
              dataset: ${dataloader.dataset}
              frequency: ${data.frequency}
            start: '{{ (app.time.start + app.time.step * 8).strftime("%Y-%m-%d") }}'
            end: '{{ (app.time.start + app.time.step * 12).strftime("%Y-%m-%d") }}'
    diagnostics:
      log:
        mlflow:
          enabled: True
          offline: True
          _target_: anemoi.training.diagnostics.mlflow.logger.AnemoiMLflowLogger
          log_model: False
          authentication: False
          tracking_uri: null
          expand_hyperparams:
            - config
          experiment_name: Nested-EAGLE-1deg15km-deterministic
          http_max_retries: 35
          on_resume_create_child: True
          project_name: Nested-EAGLE
          run_name: null
          system: False
          terminal: True
          save_dir: ${system.output.logs.mlflow}
        wandb:
          enabled: false
          entity: null+
          _target_: pytorch_lightning.loggers.wandb.WandbLogger
          offline: False
          log_model: False
          project: placeholder
          gradients: False
          parameters: False
          interval: ${diagnostics.log.interval}
      plot:
        datasets_to_plot: ["data"]
        asynchronous: false
        callbacks:
          - _target_: anemoi.training.diagnostics.callbacks.plot.PlotLoss
            dataset_names: ${diagnostics.plot.datasets_to_plot}
            every_n_batches: ${diagnostics.plot.frequency.batch}
            parameter_groups:
              moisture:
                - accum_tp
              sfc_wind:
                - u10
                - v10
          - _target_: anemoi.training.diagnostics.callbacks.plot.PlotSample
            dataset_names: ${diagnostics.plot.datasets_to_plot}
            output_steps: ${training.multistep_output}
            accumulation_levels_plot:
              - 0
              - 0.05
              - 0.1
              - 0.25
              - 0.5
              - 1
              - 1.5
              - 2
              - 3
              - 4
              - 5
              - 6
              - 7
              - 100
            colormaps: ${diagnostics.plot.colormaps}
            every_n_batches: ${diagnostics.plot.frequency.batch}
            parameters: ${diagnostics.plot.parameters}
            per_sample: 6
            precip_and_related_fields: ${diagnostics.plot.precip_and_related_fields}
            sample_idx: ${diagnostics.plot.sample_idx}
          - _target_: anemoi.training.diagnostics.callbacks.plot.PlotHistogram
            dataset_names: ${diagnostics.plot.datasets_to_plot}
            output_steps: ${training.multistep_output}
            every_n_batches: ${diagnostics.plot.frequency.batch}
            parameters:
              - gh_500
              - accum_tp
              - t2m
              - u10
              - v10
            precip_and_related_fields: ${diagnostics.plot.precip_and_related_fields}
            sample_idx: ${diagnostics.plot.sample_idx}
        frequency:
          batch: 50
          epoch: 1
        parameters:
          - gh_500
          - t_850
          - u_850
          - v_850
          - t2m
          - sh2
          - u10
          - v10
          - sp
          - accum_tp
        precip_and_related_fields:
          - accum_tp
    graph:
      overwrite: True
      nodes:
        data:
          node_builder:
            _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
            dataset: ${dataloader.training.datasets.data.dataset_config}
          attributes: ${graph.attributes.nodes}
        hidden:
          node_builder:
            _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
            dataset: ${dataloader.training.datasets.data.dataset_config}
          attributes: ${graph.attributes.nodes}
      edges:
        # Encoder
        - source_name: data
          target_name: hidden
          edge_builders:
            - _target_: anemoi.graphs.edges.KNNEdges
              num_nearest_neighbours: 12
              source_mask_attr_name: null
              target_mask_attr_name: null
          attributes: ${graph.attributes.edges}
        # Decoder
        - source_name: hidden
          target_name: data
          edge_builders:
            - _target_: anemoi.graphs.edges.KNNEdges
              num_nearest_neighbours: 3
              source_mask_attr_name: null
              target_mask_attr_name: null
          attributes: ${graph.attributes.edges}
      attributes:
        nodes:
          # Attributes for data nodes
          cutout_mask:
            _target_: anemoi.graphs.nodes.attributes.CutOutMask
          boundary_mask:
            _target_: anemoi.graphs.nodes.attributes.BooleanNot
            masks:
              _target_: anemoi.graphs.nodes.attributes.CutOutMask
          area_weight:
            _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights
            norm: unit-max
            fill_value: 0
          lam_area_weight:
            _target_: anemoi.graphs.nodes.attributes.MaskedPlanarAreaWeights
            mask_node_attr_name: cutout_mask
            norm: unit-max
        edges:
          edge_length:
            _target_: anemoi.graphs.edges.attributes.EdgeLength
            norm: unit-max
          edge_dirs:
            _target_: anemoi.graphs.edges.attributes.EdgeDirection
            norm: unit-std
    system:
      input:
        global_dataset: '{{ val.data.rundir }}/gfs.zarr'
      hardware:
        num_gpus_per_model: 1
      output:
        root: '{{ training.rundir }}/outputs/'
        logs:
          root: logs
          mlflow: mlflow
        checkpoints:
          root: checkpoint
    model:
      bounding:
        - _target_: anemoi.models.layers.bounding.ReluBounding
          variables: !list '{{ training.anemoi.data.datasets.data.processors.normalizer.config.std }}'
      num_channels: 512
      processor:
        window_size: 4320
    training:
      multistep_input: !int '{{ app.time.multistep_input }}'
      optimizer:
        _target_: torch.optim.AdamW
        betas: [0.9, 0.95]
        weight_decay: 0.01
      lr:
        iterations: ${training.max_steps}
        min: 3.e-7
        rate: 0.0000625
        warmup: 2
      max_steps: 20
      metrics:
        datasets:
          data:
            - gh_500
            - t_850
            - u_850
            - v_850
      model_task: anemoi.training.train.tasks.GraphForecaster
      scalers:
        datasets:
          data:
            general_variable:
              _target_: anemoi.training.losses.scalers.GeneralVariableLossScaler
              weights:
                accum_tp: 0.025
                default: 1
                gh: 12
                q: 0.6
                sp: 10
                t: 6
                u: 0.8
                u10: 0.1
                v: 0.5
                v10: 0.1
                w: 0.001
            node_weights:
              weight_frac_of_total: 0.1
      training_loss:
        datasets:
          data:
            _target_: anemoi.training.losses.MSELoss
            ignore_nans: false
            scalers: ["general_variable", "nan_mask_weights", "node_weights"]
      variable_groups:
        datasets:
          data:
            default: sfc
            pl:
              param:
                - gh
                - q
                - t
                - u
                - v
                - w
vx:
  grid2grid:
    global:
      wxvx:
        wxvx:
          forecast:
            name: global
            path: '{{ meta.post_files }}/global.{{ yyyymmdd[:4] }}-{{ yyyymmdd[4:6] }}-{{ yyyymmdd[6:8] }}T{{ hh }}.{{ "%02d" % fh }}h.nc'
          meta: !dict '{{ vx.common.wxvx.meta | replace("TRUTH", "grid2grid") | replace("EXTENT", "global") }}'
          paths: !dict '{{ vx.common.paths_grid | replace("TRUTH", "grid2grid") | replace("EXTENT", "global") }}'
  grid2obs:
    global:
      wxvx:
        wxvx:
          forecast:
            path: '{{ meta.post_files }}/global.{{ yyyymmdd[:4] }}-{{ yyyymmdd[4:6] }}-{{ yyyymmdd[6:8] }}T{{ hh }}.{{ "%02d" % fh }}h.nc'
          meta: !dict '{{ vx.common.wxvx.meta | replace("TRUTH", "grid2obs") | replace("EXTENT", "global") }}'
          paths: !dict '{{ vx.common.paths_obs | replace("TRUTH", "grid2obs") | replace("EXTENT", "global") }}'
visualization:
  grid2grid:
    global:
      visualization:
        eagle_tools:
          stat_prefix: grid_stat_global
  grid2obs:
    global:
      visualization:
        eagle_tools:
          stat_prefix: point_stat_global
