name: Code Quality Checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Filesystem Check/Clean
        run: .github/scripts/fsclean
      - name: Build Runtime Environment
        run: .github/scripts/build
      - name: Check Formatting
        run: .github/scripts/fmtcheck
      - name: Run Python Linter
        run: make lint
      - name: Run Python Typechecker
        run: make typecheck
      - name: Run Python Unit Tests
        run: make unittest
      - name: Run Shell Checker
        run: make shellcheck
      - name: Run YAML Linter
        run: make yamllint
      - name: Show Disk Usage
        run: set -x && df -h . && du -hs .
